#!/bin/bash

# taller 2 - Hadware y Sistemas Operativos
# -Ariel Fuenzalida
# -Henry Huerta
# -Diego Binimelis

# -INF2322-2

ARCHIVO_PROCESOS="/tmp/procesos.txt"
ARCHIVO_PANTALLA="/tmp/pantalla.txt"

pausa() {
    echo
    read -p "ENTER para continuar..."
}

listar_procesos() {
    echo
    echo "===== LISTAR PROCESOS ====="
    echo

    read -p "Ingrese usuario" usuario

    > "$ARCHIVO_PROCESOS"
    > "$ARCHIVO_PANTALLA"

    contador=1

    if [ "$usuario" = "*" ]; then
        ps -e -o pid=,user=,comm= | while read pid user comando
        do
            echo "$contador) PID: $pid Usuario: $user Comando: $comando" >> "$ARCHIVO_PANTALLA"
            echo "$pid|$user|$comando" >> "$ARCHIVO_PROCESOS"
            contador=$((contador + 1))
        done
    else
        ps -u "$usuario" -o pid=,user=,comm= 2>/dev/null | while read pid user comando
        do
            echo "$contador) PID: $pid Usuario: $user Comando: $comando" >> "$ARCHIVO_PANTALLA"
            echo "$pid|$user|$comando" >> "$ARCHIVO_PROCESOS"
            contador=$((contador + 1))
        done
    fi

    if [ -s "$ARCHIVO_PANTALLA" ]; then
        less "$ARCHIVO_PANTALLA"
    else
        echo "No se encontraron procesos."
    fi

    pausa
}


matar_proceso() {
    echo
    echo "===== MATAR PROCESO ====="
    echo

    if [ ! -s "$ARCHIVO_PROCESOS" ]; then
        echo "Primero tienes que listar procesos."
        pausa
        return
    fi

    read -p "Ingresa el numero del proceso: " numero

    contador=1
    pid_elegido=""
    usuario_elegido=""
    comando_elegido=""

    while IFS="|" read pid user comando
    do
        if [ "$contador" = "$numero" ]; then
            pid_elegido="$pid"
            usuario_elegido="$user"
            comando_elegido="$comando"
            break
        fi

        contador=$((contador + 1))
    done < "$ARCHIVO_PROCESOS"

    if [ "$pid_elegido" = "" ]; then
        echo "Numero incorrecto."
        pausa
        return
    fi

    echo "Proceso seleccionado:"
    echo "PID: $pid_elegido"
    echo "Usuario: $usuario_elegido"
    echo "Comando: $comando_elegido"
    echo

    read -p "Desea matar este proceso? (s/n): " respuesta

    if [ "$respuesta" = "s" ] || [ "$respuesta" = "S" ]; then
        kill "$pid_elegido" 2>/dev/null

        if [ $? -eq 0 ]; then
            echo "Proceso terminado correctamente."
        else
            echo "No se pudo terminar. Intentando con sudo..."
            sudo kill "$pid_elegido"

            if [ $? -eq 0 ]; then
                echo "Proceso terminado con sudo."
            else
                echo "No se pudo terminar el proceso."
            fi
        fi
    else
        echo "Operacion cancelada."
    fi

    pausa
}


Listar_detenidos(){
  echo
  echo "Buscando servicios inactivos..."
  > /tmp/servicios.txt
  contador=1

  systemctl list-units --type=service --all --state=inactive,failed --no-legend | while read -r svc load active sub description; do
    echo "$contador) $svc $descripcion" >> /tmp/servicios.txt
    contador=((contador +1))
  done

  if [ -s /tmp/servicios.txt ]; then
    less /tmp/servicios.txt
  else
    echo "No se encontrador servicios inactivos."
  fi
}

Activar_Servicio(){
  echo
  if [ ! -f /tmp/servicios.txt ] || [ ! -s /tmp/servicios.txt ]; then
    echo "Primero debes listar los servicios(Opcion 3)"
    return
  fi

  read -p "Ingresa el numero secuencial del servicio a activar: " numero
  svc_a_activar=""

  while read -r col_numero col_svc resto_linea; do
    if [ "$col_numero" == "$numero)" ]; then
      svc_a_activar="$col_svc"
      break
    fi
  done < /tmp/servicios.txt

  if [ "$svc_a_activar" != "" ]; then
    echo "Iniciando el servicio: $svc_a_activar..."
    systemctl start "$svc_a_activar" 2>dev/null
    if [ $? -eq 0 ]; then
      echo "Servicio iniciado con exito."
    else
      echo "No se pudo iniciar el servicio"
    fi
  else
    echo "Servicio no encontrado"
  fi
}


main(){

  PS3="Seleccion una opcion: "

  opciones=("Listar procesos" "Matar proceso" "listar detenidos" "activar servicio" "salir")

  select opc in  "${opciones[@]}"
  do
    case $opc in

      "Listar procesos")
        listar_procesos
        ;;


      "Matar proceso")
        matar_proceso
        ;;


      "listar_detenidos")
        Listar detenidos
        ;;


      "Activar servicio")
        activar_servicio
        ;;


      "salir")
        echo "cierre del menu"
        break
        ;;
      *)
        echo "opcion incorrecta"
        ;;
    esac
  done
}
    
