#!/bin/bash

# taller 2 - Hadware y Sistemas Operativos
# -Ariel Fuenzalida
# -Henry Huerta
# -Diego Binimelis

# -INF2322-2

Listar_procesos(){
  echo
  read -p "ingresa tu nombre: " usuario

  > /tmp/procesos.txt
  contador = 1

}


Listar_detenidos(){
  echo
  echo "Buscando servicios inactivos..."
  > /tmp/servicios.txt
  contador=1

  systemctl list-units --type=service --all --state=inactive,failed --no-legend | while read -r svc load active sub description; do
    echo "$contador) $svc $descripcion" >> /tmp/servicios.txt
    contador=((contador +1))
  done

  if [ -s /tmp/servicios.txt ]; then
    less /tmp/servicios.txt
  else
    echo "No se encontrador servicios inactivos."
  fi
}

Activar_Servicio(){
  echo
  if [ ! -f /tmp/servicios.txt ] || [ ! -s /tmp/servicios.txt ]; then
    echo "Primero debes listar los servicios(Opcion 3)"
    return
  fi

  read -p "Ingresa el numero secuencial del servicio a activar: " numero
  svc_a_activar=""

  while read -r col_numero col_svc resto_linea; do
    if [ "$col_numero" == "$numero)" ]; then
      svc_a_activar="$col_svc"
      break
    fi
  done < /tmp/servicios.txt

  if [ "$svc_a_activar" != "" ]; then
    echo "Iniciando el servicio: $svc_a_activar..."
    systemctl start "$svc_a_activar" 2>dev/null
    if [ $? -eq 0 ]; then
      echo "Servicio iniciado con exito."
    else
      echo "No se pudo iniciar el servicio"
    fi
  else
    echo "Servicio no encontrado"
  fi
}


main(){

  PS3 = "Seleccion una opcion: "

  opciones = ("Listar procesos" "Eliminar proceso" "listar detenidos" "activar servicio" "salir")

  select opc in  "${opciones[@]}"
  do
    case $opc in

      "listar procesos")
        listar_procesos
        ;;


      "Eliminar proceso")
        Eliminar_proceso
        ;;


      "listar detenidos")
        listar detenidos
        ;;


      "activar servicio"
        activar_servicio
        ;;


      "salir")
        echo "cierre del menu"
        break
        ;;
      *)
        echo "opcion incorrecta"
        ;;
    esac
  done
}
    
